### ISSUE TITLE
go minimal version documentation

### ISSUE THREAD

**Issue by northalpha** [sfudeus/isg_exporter#18]
I was running go `1.13.5` and got this error

```
# GOOS=linux GOARCH=arm GOARM=7 go build -o isg_exporter
# github.com/sfudeus/isg_exporter
./main.go:254:37: re.SubexpIndex undefined (type *regexp.Regexp has no field or method SubexpIndex)
./main.go:262:20: re.SubexpIndex undefined (type *regexp.Regexp has no field or method SubexpIndex)
```

After upgrading to `1.16.3`, everything is building as expected (and reading trough commit/merges made clear why), maybe just a hint in the documentation or releases page which minimal go version is needed or implement a quick check if the required go version is installed?

**Comment by sfudeus** [comment]
Yeah, this is re.SubexpIndex which only exists in 1.15 and was needed for "missing whitespace" support

**Comment by sfudeus** [comment]
I added a matrix build with supported versions and a trivial section about building into README.md in #19.
