### ISSUE TITLE
Scrape "hidden" pages in ISG

### ISSUE THREAD

**Issue by northalpha** [sfudeus/isg_exporter#33]
It just happend to me that i was made aware of "hidden" URLs in the ISG:

`?s=2,4` -> `ISG_DEBUG` <-- tbh not really anything really informativ
`?s=4,7` -> `EM-DEBUG-INFOS` <-- i am not sure if this is always present but it is present on my ISG with EMI.

May i ask you to incorporate this in the scraping? I am very much looking forward to `VERDICHTERDREHZAHL` ;)

**Comment by sfudeus** [comment]
Should be easy enough.
ISG_DEBUG seems to contain only data which is used for the dashboard and which has other sources. 
EM-DEBUG-INFOS does exist for me, but no data besides `WPM_TYPE`, even after enabling energy management (but without having something sg-ready attached).

**Comment by sfudeus** [comment]
Feel free to try this with release 0.8.0 and report back if it provided some help.
