### ISSUE TITLE
invalid metric name leads to crash of version 0.8.0

### ISSUE THREAD

**Issue by northalpha** [sfudeus/isg_exporter#35]
sorry my last issue #33 would have made more sense if i had attached the HTML output, that you can see that there are some "garbage" metrics

```
panic: descriptor Desc{fqName: "isg_m*1e6", help: "Metric m*1e6", constLabels: {}, variableLabels: []} is invalid: "isg_m*1e6" is not a valid metric name
```

Please find attached screenshot as well as HTML output.

<img width="517" alt="Bildschirmfoto 2021-11-07 um 21 59 21" src="https://user-images.githubusercontent.com/6721009/140661771-f827127b-f7cf-43b9-af18-1b2906352b94.png">

[isg_s4.7.html.txt](https://github.com/sfudeus/isg_exporter/files/7493083/isg_s4.7.html.txt)

**Comment by sfudeus** [comment]
fixed in #37, will release 0.8.1 in a bit
