### ISSUE TITLE
isg_explorer startet nicht im docker auf der Synology

### ISSUE THREAD

**Issue by SzymonSzumilo** [sfudeus/isg_exporter#60]
Hallo, ich versuche gerade isg_explorer zu starten (Synology, docker) - leider wird der Kontener geschlossen (Fehler ist MISSING URL) - wobei ich die URL in der Konfiguration genannt habe. Kannst du mir helfen ?

**Comment by sfudeus** [comment]
Dur URL kann man in der Konfigurationsdatei nicht setzen, entweder `--url` als direktes Kommandozeilenargument oder per Umgebungsvariable (`ISG_URL`). Das muss aktuell sogar eine richtige `http://` - URL sein, im Modbus-Modus wird naiv einfach der `http://`-Prefix abgeschnitten, um den Hostname zu bekommen.
