### ISSUE TITLE
Mode: scraping - duplicated data description at one page leads into missing one of the data values

### ISSUE THREAD

**Issue by svenoone** [sfudeus/isg_exporter#66]
I have noticed that in the "Heat Quantity" group and in the "Power Consumption" group on page ?s=1,1, the descriptions of the values are the same. I suspect that existing data with the same description are overwritten with a newer data value, as I can only read the latest values.

![image](https://user-images.githubusercontent.com/47710373/226207783-ca538af8-1792-4345-9af6-9d48dc5eb50a.png)

ISG v12.2.1 + WPE-I 12H 230 Premium

**Comment by svenoone** [comment]
I made a fix for this issue and created a pull request https://github.com/sfudeus/isg_exporter/pull/68

**Comment by sfudeus** [comment]
Hey, thanks for reporting - sorry for the long delay, but it was just a little below a full year ;-). 
And thanks for the fix as well. The only reason I am hesitant to use/adapt that is that it will change the metrics names for all users. 
With my LWZ, StiebelEltron was smart enough to have all the names unique, so I hadn't had the problem. 
Maybe a "legacy mode" could be introduced to support both metric naming modes. 
I'll see if I can get into this.

**Comment by svenoone** [comment]
I can understand that :) It's primarily my problem, not yours. I get on quite well with my fix. Since I didn't have any old data, I didn't have to rewrite the DB. That would be an alternative solution. If you work with Grafana, you have to map the new variables anyway, if you don't throw out the old ones, the data will remain in the same diagram.

**Comment by sfudeus** [comment]
Were you able to test this one already? This would be branch support_non-unique-metric-names or docker image docker.io/sfudeus/isg_exporter:preview-93. Only fixing the prefixing, not the on/off from the other issue. 

I'm not 100% happy to go on "Legacy" by default, but as you say, breaking metrics for those who do (auto-) update without the release notes is suboptimal as well. 
Eventually, I'd switch the default.

**Comment by sfudeus** [comment]
docker.io/sfudeus/isg_exporter:preview-93 and the branch are now including the onoff fix, rebased from main.

**Comment by svenoone** [comment]
Tested today, the parameter --metricsWithSectionPrefix. I can confirm the result works as expected. I have that not tested in different languages, just in German.
