### ISSUE TITLE
ISG release 12.1.2 white space issues

### ISSUE THREAD

**Issue by northalpha** [sfudeus/isg_exporter#7]
... in the upcoming release of ISG `12.1.2` (due to some circumstances i already have it on my ISG Web)

There are subtile changes to the webpage for example there is an whitespace removed between the value and the unit

Version `12.1.2`
![Screenshot 2021-02-04 at 16 48 36](https://user-images.githubusercontent.com/6721009/106917963-1505cb80-6709-11eb-9b18-c63ee7f6b053.png)

before:

![isg_pre_12 1 2](https://user-images.githubusercontent.com/6721009/106918537-92314080-6709-11eb-8985-2293eec911d4.png)

I am by no means someone wo is able to wrote code, but maybe you can hint me a small code snipped to change to get this working again, would be very nice :)

**Comment by sfudeus** [comment]
I'll try to look into it later, should be trivial enough. I cannot test it since my ISG is currently sent in for update.

**Comment by northalpha** [comment]
DM me on Twitter or send me patches ... i am more than happy to help und test :)

**Comment by sfudeus** [comment]
@northalpha Can you try docker image tag 0.5.6-3-g64fdcb3_1.15.7? That should do the trick. If it works, I'll publish as 0.5.7.

**Comment by northalpha** [comment]
I am not running the docker image but i am cross-compiling the go for raspberry pi from #8 and can confirm it is working, i got all the data back! thank you for the quick fix!

**Comment by sfudeus** [comment]
Interesting, I had problems compiling for arm because of one dependency library. Need to check that again. Do you use cgo or not?

**Comment by northalpha** [comment]
Yes, i "hacked" it via changing 

`/pkg/mod/github.com/headzoo/surf@v1.0.0/agent/agent_linux.go`

`35: func charsToString(ca [65]int8) string {`
to
`35: func charsToString(ca [65]uint8) string {`

and than cross compiling (running mac os here) for arm via:

`GOOS=linux GOARCH=arm GOARM=7 go build -o isg_exporter`

**Comment by sfudeus** [comment]
d'oh - they had that fixed in surf (in 2017), but didn't release a version since. Multiarch compatibility and build be fixed with #11.
