### ISSUE TITLE
Negative values and not read correctly

### ISSUE THREAD

**Issue by northalpha** [sfudeus/isg_exporter#9]
Due to the weather right now i have noticed that values from ISG that are negative in value (VERDAMPFERTEMP or AUSSENTEMPERATUR) are not read correctly:

Real (shown on ISG) : `-6°`
Read: `6°`

i think the `-` indicator is being stripped.

**Comment by sfudeus** [comment]
oh, that might have happened because of the whitespace fix, well fix later
